[package]
name = "nmea0183-rustgw"
version = "0.1.0"
authors = ["Anders Arnholm <anders@arnholm.se>"]
edition = "2018"

[[bin]]
name = "ws-server"
path = "src/bin/ws-connection.rs"

[[bin]]
name = "tcp-provider"
path = "src/bin/tcp-provider.rs"

[dependencies]
ws = "*"
serde_json = "1.0.39"